### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by magical** [OSULUG/OSULUG-Website#134]
I just noticed (for the nth time) that the LUG site is inaccessible over HTTPS because we're serving up an invalid certificate. 

https://lug.oregonstate.edu/

We should fix that.

**Comment by dgrocki** [comment]
Do we need to renew an ssl certificate? Any idea what we are using or where
to check?

**Comment by magical** [comment]
I'm not sure. The certificate that's being served up is only valid for beaverbarcamp.org, so I assume something is misconfigured somewhere.

**Comment by TravisWhitehead** [comment]
The incorrect certificate had to do with how the Open Source Lab's HAProxy configuration is set up...

I emailed support@osuosl.org and requested an SSL certificate (because it's ridiculous not to have HTTPS in this day and age). It's set up now, but some of the resources on the site are still served with HTTP. >.>

**If anyone wants to work on this issue, please update the resources to use HTTPS (e.g. remote CSS files) and any other mixed content.**

**Comment by drewsortega** [comment]
moved to new GitLab site, https://gitlab.com/osu-lug/projects/web/lug-web. Closing.
